version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34.5
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-54-247-189-1.eu-west-1.compute.amazonaws.com
            port: '5432'
            database: dtd58t1fpp2dm
            ssl: true
            user: vgkuebjwtxklep
            password: c7cedc75a8ab6a7dd295f6af53089995f2d8413178e5353f7f54e50fb91cd3f3
            migrations: true